# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherUIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WeatherUIKit
  pod 'Moya', '~> 15.0'

  # or

  pod 'Moya/RxSwift', '~> 15.0'
  
  # or

  pod 'Moya/ReactiveSwift', '~> 15.0'

  #or

  pod 'Moya/Combine', '~> 15.0'


  target 'WeatherUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherUIKitUITests' do
    # Pods for testing
  end

end
